use daoju001;
CREATE TABLE `t_agent` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nick` varchar(50) DEFAULT '' COMMENT 'QQ connect 昵称',
  `qq_connect_id` varchar(255) DEFAULT '' COMMENT 'QQ connect 唯一ID',
  `password` varchar(50) DEFAULT NULL COMMENT '登录密码',  
  `company_name` varchar(50) DEFAULT NULL COMMENT '公司名称',
  `brand_name` varchar(50) DEFAULT NULL COMMENT '代理品牌名称',
  `logo` varchar(50) DEFAULT NULL COMMENT '品牌logo',
  `address` varchar(50) DEFAULT NULL COMMENT '公司地址',
  `phone` varchar(50) DEFAULT NULL COMMENT '公司电话',
  `fax` varchar(50) DEFAULT NULL COMMENT '公司传真',
  `description` varchar(50) DEFAULT NULL COMMENT '公司介绍',
  `verified_link` varchar(50) DEFAULT NULL COMMENT '证书链接',
  `contact_name` varchar(50) DEFAULT NULL COMMENT '联系人名称',
  `contact_phone` varchar(50) DEFAULT NULL COMMENT '联系人手机',
  `contact_qq` varchar(50) DEFAULT NULL COMMENT '联系人QQ',
  `contact_email` varchar(30) DEFAULT NULL COMMENT '联系人邮箱',
  `reg_time` TimeStamp COMMENT '注册时间',
  `gmt_create` TimeStamp COMMENT '记录创建时间',
  `gmt_modified` TimeStamp COMMENT '记录修改时间(最近登录时间)',
  PRIMARY KEY (`Id`),
  KEY (`company_name`),
  KEY (`nick`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='代理商表';
